<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Ort-o-Matic</title>

		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/bootstrap-theme.min.css" rel="stylesheet">
		<link href="/css/orto.css" rel="stylesheet">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	</head>
	<body>
		
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12">

					<ul class="nav nav-tabs" style="margin-top: 10px;">
						<li style="font-size: 18px; line-height: 40px; margin-right: 15px;">Ort-o-Matic</li>
						<?php
						$menu = [
							[
								'controller' => 'index',
								'name' => 'Dashboard',
							],
							[
								'controller' => 'export',
								'name' => 'Export dati',
							],
							[
								'controller' => 'config',
								'name' => 'Configurazione',
							],
						];
						
						foreach ($menu as $item) {
							$attrs = '';
							if ($item['controller'] == $this->className) {
								$attrs = 'class="active"';
							}
							echo "<li $attrs><a href=\"$item[controller]\">$item[name]</a></li>";
						}
						?>
					</ul>
					
				</div>
			</div>
