<div class="row">
	<div class="col-md-6">
		<h2>Valori fisici attuali</h2>
		<canvas id="humidity" width="350" height="350" style="width:50%"></canvas>
		<canvas id="thermoP" width="105" height="340" style="width:16%"></canvas>
		<canvas id="thermoA" width="105" height="340" style="width:16%"></canvas>
		<p class="col-md-offset-3">
			Umidità <span class="vaso">vaso</span>: <?php echo $humidity; ?> %rel.<br>
			Temperatura <span class="vaso">vaso</span>: <?php echo $t0; ?> °C.<br> 
			Temperatura <span class="laboratorio">laboratorio</span>: <?php echo $t1; ?> °C.
		</p>
		
		<h3>Diretta webcam</h3>
		<div class="img-home-preview">
			
			<img src="/canopypreview.jpg" class="canopy img-responsive">
			<img src="/webcam.jpg" class="real img-responsive">
		</div>
	</div>
	
	<div class="col-md-6">
		<h2>Serie storiche</h2>
		<canvas id="historyH" width="600" height="250" style="width:95%"></canvas>
		<p>Umidità, ultime 24 ore [%rel]</p>
		<canvas id="historyT" width="600" height="250" style="width:95%"></canvas>
		<p>Temperatura: <span class="vaso">vaso</span> e <span class="laboratorio">laboratorio</span>, ultime 24 ore [°C]</p>
		<canvas id="historyC" width="600" height="250" style="width:95%"></canvas>
		<p>Canopy, ultimi 7 giorni [kpx]</p>
	</div>
</div>

<script>
	$(document).ready(function ()
	{
		var humidity = <?php echo $humidity; ?>,
			t0 = <?php echo $t0; ?>,
			t1 = <?php echo $t1; ?>,
			serieH = <?php echo json_encode($serieH); ?>,
			serieC = <?php echo json_encode($serieC); ?>,
			serieT0 = <?php echo json_encode($serieT0); ?>,
			serieT1 = <?php echo json_encode($serieT1); ?>;
		
		new RGraph.Gauge('humidity', 0, 100, humidity).grow();
		new RGraph.Thermometer('thermoP', 0, 50, t0).grow();
		new RGraph.Thermometer('thermoA', 0, 50, t1).set('colors', ['orange']).grow();
		
		new RGraph.Line('historyT', serieT0.values)
			.set('colors', ['orange'])
			.set('labels', serieT0.labels)
			.set('ymin', 10)
			.set('ymax', 40)
			.draw();

		new RGraph.Line('historyT', serieT1.values)
			.set('colors', ['red'])
			.set('ymin', 10)
			.set('ymax', 40)
			.draw();
	
		new RGraph.Line('historyH', serieH.values)
			.set('colors', ['blue'])
			.set('labels', serieH.labels)
			.set('ymin', 0)
			.set('ymax', 100)
			.draw();
	
		new RGraph.Line('historyC', serieC.values)
			.set('colors', ['green'])
			.set('labels', serieC.labels)
			.draw();
		
	})
</script>